### ISSUE TITLE
Extend example for `returnMulti`

### ISSUE THREAD

**Issue by hseeberger** [markus1189/mockito-scala#1]
We should add one more invocation to demonstrate what happens when we invoke more often than the number of given values:

``` scala
{ // Specifying multiple returns
    val m = mock[Foo]

    m.bar returnsMulti Seq("1", "2", "3")
    m.bar // => "1"
    m.bar // => "2"
    m.bar // => "3"
    m.bar // => "3"
  }
```

Not sure if "3" is correct, hence my interest in this topic ;-)

**Comment by markus1189** [comment]
Agreed, that should be added as an example.  It is the way mockito behaves with chained `thenReturn` so I guess it is "correct" ;)
